### ISSUE TITLE
Store geojson of the locations on the ES index

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/biothings_covid19#17]
See outbreak-info/outbreak.info#134 

Currently, the choropleths at outbreak.info/maps are loaded as [geojsons](https://github.com/SuLab/outbreak.info/tree/master/web/src/assets/geo) by the front-end and then merged with the result of an API call client-side. Obviously, this puts a load on the front-end, and the join can't be cached for subsequent calls.

1. Investigate the performance hit on the API by storing this additional info on the backend and the query time on the front-end vs. the current behavior.
2. If it looks good: add the geojsons for each region to every data point.
3. Adjust the front-end to query rather than run the join client-side.

**Comment by gkarthik** [comment]
Fixed by https://github.com/outbreak-info/biothings_covid19/commit/92f1f8f324d4d40dd9143db7e3fa6ad63dc9323e
